### PR TITLE
Fix Bézier calculation; support H/V/S/T commands

### LINKED ISSUE #8: Does not work correctly with Bézier commands
The JS code below produces the SVG file shown. There are 1, 2, 3, and 4 quadrants of a circle created using cubic Bézier commands, and then these paths are sampled using 10, 20, 30, and 40 points.

bad-points

---

```js
const measurablePath = require('point-at-length');
const paths = {
  '10' : 'M15,25 c 5.5191502449,0 10,-4.4808497551 10,-10',
  '20' : 'M40,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10',
  '30' : 'M65,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10 s-10,4.4808497551 -10,10',
  '40' : 'M90,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10 s-10,4.4808497551 -10,10 s4.4808497551,10  10,10 z'
};

console.log('<?xml version="1.0" encoding="utf-8"?>');
console.log('<svg xmlns="http://www.w3.org/2000/svg" width="840px" height="480px" viewBox="0 0 105 60">');
console.log('<style>path, polyline { fill:none; stroke:black; stroke-width:0.5px }');
console.log('polyline { stroke:red }</style>');
for (const steps in paths) {
  const d = paths[steps],
        path = measurablePath(d),
        len = path.length(),
        pts = [];
  for (var i=0;i<steps;++i) pts.push(path.at(len*i/steps));
  console.log('<path d="'+d+'"/>');
  console.log('<polyline points="'+pts.join()+'" transform="translate(0,25)"/>');
}
console.log('</svg>');
```

---

```xml
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" width="840px" height="480px" viewBox="0 0 105 60">
<style>path, polyline { fill:none; stroke:black; stroke-width:0.5px }
polyline { stroke:red }</style>
<path d="M15,25 c 5.5191502449,0 10,-4.4808497551 10,-10"/>
<polyline points="15,25,16.649181985275018,24.955268577529207,18.295981745836844,24.856040236194854,19.933979104737535,24.663230389522443,21.413417385378374,24.018724008548762,22.415294996147626,22.709078082251374,23.2746905770652,21.301538238591164,23.983467682598565,19.812516647717548,24.524537496938407,18.254824892971982,24.874166215879935,16.643563226758143" transform="translate(0,25)"/>
<path d="M40,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10"/>
<polyline points="40,25,40.824783839428626,24.9847975832476,41.64918198527502,24.955268577529207,42.47300959053456,24.91272711881043,43.29598174583685,24.85604023619485,44.11701901909349,24.776401743741935,44.93397910473753,24.663230389522443,45.734735962679316,24.46953745728016,46.41341738537838,24.018724008548766,46.93292527909861,23.37818047566017,47.41529499614762,22.709078082251374,47.86298893778751,22.01629453747637,48.2746905770652,21.30153823859116,48.64878789060059,20.566406881235036,48.98346768259857,19.812516647717548,49.276207824502876,19.041378667864326,49.52453749693841,18.25482489297198,49.724956648100715,17.454739292173464,49.87416621587993,16.643563226758143,49.96759820544199,15.824105538869857" transform="translate(0,25)"/>
<path d="M65,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10 s-10,4.4808497551 -10,10"/>
<polyline points="65,25,65.54989144492649,24.991756396281893,66.09962883446815,24.976266504123146,66.64918198527502,24.955268577529207,67.19849721788933,24.928764914751625,67.74749543154758,24.89628669657628,68.29598174583684,24.85604023619485,68.84370003036602,24.806484409727453,69.39021503356432,24.74512569362011,69.93397910473753,24.663230389522443,70.4721610024806,24.55084197054614,70.987200455325,24.36122863914973,71.41341738537838,24.018724008548777,71.76461151965555,23.595625788786528,72.09748716388603,23.157882007852873,72.41529499614762,22.709078082251377,72.71766898214025,22.2497342057627,73.00430493929822,21.78040902030762,73.2746905770652,21.30153823859116,73.528383368777,20.813620226195923,73.76484672144143,20.31712377015387,73.98346768259856,19.812516647717548,74.1834147205866,19.300224406052237,74.36407688558165,18.78082014380898,74.52453749693841,18.25482489297198,74.6636409438304,17.722788068844793,74.78062792867922,17.185461794119174,74.87416621587992,16.643563226758143,74.94282123609814,16.09796059447044,74.98519368891586,15.549696896228593" transform="translate(0,25)"/>
<path d="M90,25 c 5.5191502449,0 10,-4.4808497551 10,-10 s-4.4808497551,-10 -10,-10 s-10,4.4808497551 -10,10 s4.4808497551,10  10,10 z"/>
<polyline points="90,25,90.76588540834169,24.98628857819015,91.53147104413718,24.960665552434858,92.2965585676675,24.923035890947325,93.06094444374773,24.873286645485745,93.82417579630386,24.808273568555414,94.58470710011014,24.7174326532894,95.33832397295224,24.582072838208187,96.05536923064155,24.322191477710398,96.60477291624747,23.794660052941513,97.07429952725832,23.18950353102498,97.514266635388,22.562515363720976,97.92407428985132,21.9154142951275,98.30274787766581,21.249618205051352,98.64883059741825,20.566317366931106,98.96086844398378,19.866819661954903,99.23702661503324,19.15240242275914,99.47516326059436,18.424435546299524,99.67290262410779,17.68448135833669,99.82717975383083,16.934270156915858,99.93461648663656,16.17595247472275,99.99147680785708,15.412205222321083,99.7498948036681,15.250105196331896,99.2082339812421,15.791766018757903,98.6665731588161,16.333426841183908,98.1249123363901,16.87508766360991,97.58325151396407,17.41674848603592,97.04159069153808,17.95840930846192,96.49992986911207,18.500070130887934,95.95826904668607,19.041730953313937,95.41660822426006,19.583391775739944,94.87494740183405,20.125052598165947,94.33328657940805,20.666713420591954,93.79162575698203,21.208374243017957,93.24996493455603,21.750035065443967,92.70830411213002,22.291695887869974,92.16664328970401,22.833356710295977,91.62498246727802,23.37501753272198,91.083321644852,23.916678355147987,90.54166082242601,24.458339177573993" transform="translate(0,25)"/>
</svg>
```

### PR DESCRIPTION
**Pull request by Phrogz**
This pull request includes the pull request #7 from Polymagine / @d-nivot-polymagine, and fixes #8

### CODE REVIEW

**Comment by Phrogz** [comment]
Ping! Have you a chance to look at this and consider merging?

**Comment by emeeks** [comment]
@Phrogz This doesn't seem actively maintained anymore maybe you could fork it if you have the time to continue development?

**Comment by Phrogz** [comment]
@emeeks Well, you can always clone [my fork](https://github.com/Phrogz/point-at-length) of the repo to get these changes. I'm not sure how one goes about forking an npm repo, though. I guess I would have to just publish my own derivative under a new package name?

**Comment by mkaemmerer** [comment]
These look like some great changes @Phrogz and @d-nivot-polymagine. Thanks!

I don't know that I would describe my current ~level~ lack of involvement as "maintaining" this repo, but I'm *currently* paying enough attention to merge and publish this.

If you ask @substack, he may be willing to give you write access to this repo if you're interested in/willing to maintain it in the future

**Comment by Phrogz** [comment]
Thanks, @mkaemmerer

**Pull request merged**
